# Generated by Django 3.2.13 on 2022-07-07 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20220628_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipes.category'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(default='Please Use bulletpoints for each ingredient'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='method',
            field=models.TextField(default=' Please Use numbered list for each method step'),
        ),
    ]
